### ISSUE TITLE
Migrate backend and UI to an async lib

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#10]
Our current backend module is inspired from the [Will of Steel API Wrapper](https://github.com/WillofSteel-Devs/api-wrapper) which uses a synchronous library (requests) for processing HTTP Requests to the API.

But, using a async library such as `aiohttp` would be the best on this project. 

I'm not 100% sure but I do believe requests module will block the tkinter loop for the time it's processing, which could lead to lag/hang on the application. 

I will be making a PR for this issue, or if anyone wants to take it up, feel free!

**Comment by ItsNeil17** [comment]
This will also require porting the main GUI to an async library such as:

- [async-tkinter-loop](https://pypi.org/project/async-tkinter-loop/)
- [asynctkinter](https://pypi.org/project/asynctkinter/)

or potentially use [tkinter-async-execute](https://pypi.org/project/tkinter-async-execute/) for any requests to the API? TAE does not require us to change what we currently have (even though it's not a lot). All we would have to change is the functions we use from the backend, which if I'm not wrong we don't use any. 

I'm confused on what approach to move forward with for this. Let me know your opinion @y345-git @Were-Woof

**Comment by Were-Woof** [comment]
At a glance I'm happy with all of these options, though I'll need to look in more detail to have a final answer.

If those don't work out, a solution I used on a previous object to solve a similar issue was the inbuilt threading library, however these other library options should be explored first since if we get them working they are a better solution.

**Comment by ItsNeil17** [comment]
Did you get a chance to look at them? @Were-Woof

**Comment by Were-Woof** [comment]
Yep, I'm thinking either asynctkinter or tkinter-async-execute, though either of those options work for me

**Comment by ItsNeil17** [comment]
Implemented with 1b9e343

------------
Commit ID: 1b9e343
Commit: feat: Add aiohttp for async HTTP requests in API class
Commit Verified: ✅
PR Check Bypassed - commit on branch `main`
Full Commit ID: `1b9e34322a42717f371fa1f9a43b28a6ff87e59e`
Permanent commit link: `https://github.com/WillofSteel-Devs/app/commit/1b9e34322a42717f371fa1f9a43b28a6ff87e59e`
