### ISSUE TITLE
API Menu

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#17]
Store API Key & check on startup if it is available. Hit the `/verify` (with the correct headers) endpoint to see if it works, if it's invalid, ask for a API Key (required menu)

`/verify` is purposefully not documented in the API, ask me any questions regarding it if necessary. 

The API Wrapper already has an example of this:
```py
# willofsteel/client.py
    def _verify_key(self) -> None:
        response = self.request("GET", "/verify", self.headers)
        if response.status == 403:
            raise InvalidKey
        elif response.status == 200:
            logging.info("Key verification successful.")
        else:
            raise ServerError
```

### Linked PRs
* gh-18

**Comment by y345-git** [comment]
So, Basically a new menu on startup ?

**Comment by ItsNeil17** [comment]
You first check if the file you store it is in preset or not, and if it has the API Key, then you check if that key is valid using a verify endpoint. 

The API Wrapper already has an example of this: 
https://github.com/WillofSteel-Devs/api-wrapper/blob/main/willofsteel/client.py#L34-L41

**Comment by CozmoKitten** [comment]
does anyone know where the colours of frames are stored (like the blue on the NPC background) ? I can't see to find it anywhere.

**Comment by CozmoKitten** [comment]
nevermind, I found it

**Comment by ItsNeil17** [comment]
> does anyone know where the colours of frames are stored (like the blue on the NPC background) ? I can't see to find it anywhere.

Background colors for frames are stored inside their frame with the param `bg` 
https://github.com/WillofSteel-Devs/app/blob/1f1790c3096b0fa0a9850917c572527ab5f50e98/gui/frames/npc.py#L7
