### ISSUE TITLE
Alliance Management Menu

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#24]
Add a frame to view/manage your Alliance, you should be able to:

- view your alliance (bank, name, userlimit etc)
- update your alliance name
- update your alliance user limit
- ~~deposit to your alliance~~ API support not available, TBD
- ~~view members of your alliance~~ TBDL

FULL API support is available for this.

### Linked PRs
* gh-32

**Comment by Owen-Griffin** [comment]
I got this one

**Comment by Owen-Griffin** [comment]
Completed code untested due to broken API. Created PR at request of @ItsNeil17.

**Comment by Owen-Griffin** [comment]
Can this be closed @ItsNeil17?
