### ISSUE TITLE
Outposts

### ISSUE THREAD

**Issue by Owen-Griffin** [WillofSteel-Devs/app#30]
- Must display all outposts and their names
- Ideally works with more/less outposts, in case some are added/removed

### Linked PRs
* gh-39

**Comment by ItsNeil17** [comment]
There are only 15 outposts atm so we can just hard code it.

**Comment by Owen-Griffin** [comment]
I will do this since it actually has API support.

**Comment by Owen-Griffin** [comment]
@ItsNeil17 can I have your opinion on this? My problem is I can't center the names properly since their length is variable.

**Comment by ItsNeil17** [comment]
@Owen-Griffin I had something else in mind regarding this. I thought of an idea where the name would be at the top, with a capture button below it. I have attached a screenshot below for reference. Ofcourse it won't be 1:1 but I would want something like this. 

![image](https://github.com/WillofSteel-Devs/app/assets/68216747/6ca67933-e73c-40ab-aa17-ebd412b82f6d)

**Comment by ItsNeil17** [comment]
> @ItsNeil17 can I have your opinion on this? My problem is I can't center the names properly since their length is variable.

Also length would be 25 characters max, so if we're going forward with the idea above, we just allow extra space for 25 chars.

**Comment by Owen-Griffin** [comment]
Alright, I'll look at implementing that.

**Comment by Owen-Griffin** [comment]
okay so its 300 lines of code, but it works.
