### ISSUE TITLE
Empty Frame

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#31]
Just a empty frame with no widgets for placeholder purposes like 
https://github.com/WillofSteel-Devs/app/blob/97888c8db0a6645564a1b1b80cd832163f869085/gui/app.py#L38

### Linked PRs
* gh-34

**Comment by Owen-Griffin** [comment]
Alright, I'll start work on this.

**Comment by ItsNeil17** [comment]
Was just about to do this and then saw on my git log that a new branch was created. Cool
