### ISSUE TITLE
API key frame label doesnt cover the whole screen

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#47]
### Expected Results

API frame label to cover the whole screen

### Actual Results

It doesn't 

### Steps to Reproduce

Run the app, click on api key bottom left 

### App Version

0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details regarding this issue.
- [x] I have removed my API Key from display, if visible.

### Linked PRs
* gh-59

**Comment by Owen-Griffin** [comment]
@ItsNeil17 are you okay with a separate frame for the initial entry and later entry? Otherwise, I don't think there is a simple way to do this.

**Comment by ItsNeil17** [comment]
Why don't we just accept a parameter `sidebar` on the frame, if the sidebar param is true, we don't change anything, if it's not we change the width of the frame label?

**Comment by Owen-Griffin** [comment]
okay, that makes sense. I'll finish this later today

**Comment by ItsNeil17** [comment]
Have you had a chance to look at 

- #49 
- #51
