### ISSUE TITLE
Entering ridiculous values in the NPC attack works for some reason

### ISSUE THREAD

**Issue by y345-git** [WillofSteel-Devs/app#56]
### Expected Results

Give an output with saying invalid amount of troops / you dont have that many troops or smth.

### Actual Results

![image](https://github.com/WillofSteel-Devs/app/assets/66121022/bff45466-b0d0-429e-977e-c85d7e7ba549)
![image](https://github.com/WillofSteel-Devs/app/assets/66121022/2be9a382-5843-481e-941c-b39dd2e9137e)

### Steps to Reproduce

Go to the NPC tab on sidebar and enter any number value in any of the troops. The attack goes thru and considers it as a win.

### App Version

0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details regarding this issue.
- [X] I have removed my API Key from display, if visible.

**Comment by ItsNeil17** [comment]
Fixed in the APi
