### ISSUE TITLE
Nothing happens when I modify Alliance information

### ISSUE THREAD

**Issue by y345-git** [WillofSteel-Devs/app#57]
### Expected Results

Edit the Alliance properties

### Actual Results

![image](https://github.com/WillofSteel-Devs/app/assets/66121022/4c63f05b-0977-4db7-8e47-84b1e427c182)
Basically, nothing happens except emptying the text you entered.

### Steps to Reproduce

Go to the alliance tab and then enter any of the values to be changes, The name or the user limit.

### App Version

0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details regarding this issue.
- [X] I have removed my API Key from display, if visible.

**Comment by ItsNeil17** [comment]
Fixed with 7eb011f
