### ISSUE TITLE
Buttons in Construction tab do nothing.

### ISSUE THREAD

**Issue by y345-git** [WillofSteel-Devs/app#58]
### Expected Results

Possibly upgrade the respective buildings / show insufficient funds.

### Actual Results

Does nothing. 
![image](https://github.com/WillofSteel-Devs/app/assets/66121022/c145b540-f9d8-4fea-8461-5fb3e332e206)

### Steps to Reproduce

Go to the Construction tab and click on any of the 3 upgrade buttons.

### App Version

0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details regarding this issue.
- [X] I have removed my API Key from display, if visible.

**Comment by ItsNeil17** [comment]
Fixed with b3c8a0b
