### ISSUE TITLE
Troops GUI value does not update.

### ISSUE THREAD

**Issue by y345-git** [WillofSteel-Devs/app#62]
### Expected Results

Update the GUI value with the actual value after an attack.

### Actual Results

![image](https://github.com/WillofSteel-Devs/app/assets/66121022/814e87e9-e197-4358-bcbe-55474ffe4b26)

### Steps to Reproduce

Attack a NPC and then check back with values of your troops in this GUI.
![image](https://github.com/WillofSteel-Devs/app/assets/66121022/7c9ab73c-5098-4da8-a471-fb465749b16e)

### App Version

0.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details regarding this issue.
- [X] I have removed my API Key from display, if visible.

### Linked PRs
* gh-65

**Comment by ItsNeil17** [comment]
The screenshots you displayed display an error 
![image](https://github.com/WillofSteel-Devs/app/assets/68216747/61705281-3dde-435b-a23e-b5bd5d586f6a)

This is still a bug, the error message should be handled accordingly. @Owen-Griffin
