### ISSUE TITLE
Construction

### ISSUE THREAD

**Issue by ItsNeil17** [WillofSteel-Devs/app#7]
- Must be able to display information about the price and current state of the player's constructions and their upgrades
- Must be able to select a "building" to upgrade
- Must give feedback when a building is upgraded

### Linked PRs
* gh-36

**Comment by ItsNeil17** [comment]
API support to be added, please use the following as a reference:

## GET `/buildings` 

Expected response 200:

```json
{
    "success": true,
    "farmhouse_level": 1,
    "bakery_level": 1,
    "storehouse_level": 1,
    "production": 1,
}
```

## POST `/buildings`

Query Parameters:

| query_param | expected_type | example |
|----------------|-----------------|-----------|
| building | str | farmhouse |
| level (optional) | int | 1 |

- `building` - the building you want to upgrade
- `level` - how many levels you want to upgrade

All responses *may* error with the follow status codes:

- 403 - Access Forbidden
- 422 - Validation error

**Comment by CozmoKitten** [comment]
I'll take this one

**Comment by CozmoKitten** [comment]
Now that I'm coding this, it appears to me that when you said "API support to be added," you meant it wasn't there yet. I'll do a little more, but I can't do the actual UI design until @ItsNeil17 adds API support, so that I can test it with actual data to ensure fit.

**Comment by CozmoKitten** [comment]
Made some progress. I've added the back-end API bits, to spec with Neil's original message. I've added upgrade buttons and labels to the GUI, along with a label to display the levels (untested due to the lack of API support). That's all for now.

**Comment by ItsNeil17** [comment]
You don't need to build a new instance of `Backend` in each frame, you can access the global one by doing `self.parent.backend`. 

Ref: 
https://github.com/WillofSteel-Devs/app/blob/b7d924be4d9f74ccb601f427c230b4de6882a1bc/gui/frames/construction.py#L29-L35

**Comment by ItsNeil17** [comment]
@Owen-Griffin API support is added, I've tested this with my local environment and it works with a few changes that I'll be pushing. 

Please make a PR for this

**Comment by Owen-Griffin** [comment]
@ItsNeil17 on my testing, API returns a 404 not found error (api.willofsteel.me/buildings)

**Comment by ItsNeil17** [comment]
Buildings has not been published yet due to the lack of documentation at this moment. I've tested with my local environment and it works

**Comment by Owen-Griffin** [comment]
Okay. Should I create the PR?

**Comment by ItsNeil17** [comment]
👍
